apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: marco-paul237/schoolbridge-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: schoolbridge-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: schoolbridge-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: schoolbridge-secrets
              key: JWT_SECRET
        volumeMounts:
        - name: cv-storage
          mountPath: /app/uploads/cvs
      volumes:
      - name: cv-storage
        persistentVolumeClaim:
          claimName: cv-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
